# Generated by Django 5.2.5 on 2025-08-30 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('scan_type', models.CharField(choices=[('website', 'Website'), ('instagram', 'Instagram'), ('social_media', 'Social Media'), ('other', 'Other')], max_length=20)),
                ('risk_score', models.IntegerField(default=0, help_text='Risk score from 0-100')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='low', max_length=20)),
                ('domain_age', models.IntegerField(blank=True, help_text='Domain age in days', null=True)),
                ('ssl_valid', models.BooleanField(default=False)),
                ('has_contact_info', models.BooleanField(default=False)),
                ('scam_keywords_found', models.JSONField(blank=True, default=list)),
                ('content_analysis', models.JSONField(blank=True, default=dict)),
                ('community_reports', models.IntegerField(default=0)),
                ('accuracy_score', models.FloatField(default=0.0, help_text='Community accuracy rating 0.0-1.0')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accurate', models.BooleanField(default=True, help_text='Whether the report was accurate')),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scan_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='scanner.scanresult')),
            ],
        ),
    ]
